# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dogmen' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dogmen
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

#    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#    pod 'React', :path => '../node_modules/react-native'
#    pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  target 'Dogmen-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DogmenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Dogmen-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dogmen-tvOS

 
end
